create table if not exists public.stories (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    seed text not null,
    title text not null,
    story_mode text not null,
    country text default '',
    status text not null default 'BLUEPRINT_REVIEW',
    blueprint jsonb not null default '{}'::jsonb,
    production jsonb not null default '{}'::jsonb,
    distribution jsonb not null default '{}'::jsonb,
    performance jsonb not null default '{}'::jsonb
);

create index if not exists stories_status_idx on public.stories(status);
create index if not exists stories_updated_at_idx on public.stories(updated_at desc);

-- Keep the PostgREST surface closed. MORQEVA connects server-side through PostgreSQL.
alter table public.stories enable row level security;
